name = "UAG Modpack - Operations"
prefix = "UAG_Modpack_Operations"
mainprefix = "z"

[version]
major = 0
minor = 0
patch = 0
git_hash = 8

[properties]
author = "UAG Development Team"
url = "https://github.com/uagpmc/arma3"